#!/bin/sh

# Modules here can be loaded late

start() {
	printf 'Loading tj028 extra modules: '
	/usr/sbin/modprobe fat
	/usr/sbin/modprobe vfat
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

case "$1" in
	start)
		"$1";;
	*)
		echo "Usage: $0 {start}"
		exit 1
esac

